version: "3"

services:
  api:
    container_name: nolaborables
    restart: always
    build: .
    ports:
      - "3100:8080"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules

volumes:
  node_modules:
